<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;netstandard2.0;net472;</TargetFrameworks>
    <Version>2.0.0-preview.1</Version>
    <Description>
      A lightweight implementation of Linger.HttpClient.Contracts using standard .NET HttpClient.
      Provides typed response parsing, per-request headers, and streaming file transfers.
      Seamlessly integrates with .NET's HttpClientFactory for optimal connection management.
    </Description>
</PropertyGroup>

  <ItemGroup>
</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net472'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Linger.HttpClient.Contracts\Linger.HttpClient.Contracts.csproj" />
    <ProjectReference Include="..\Linger.Json\Linger.Json.csproj" />
    <ProjectReference Include="..\Linger\Linger.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.301" />
  </ItemGroup>

</Project>
