<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0;net472</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Linger.HttpClient.Contracts\Linger.HttpClient.Contracts.csproj" />
        <ProjectReference Include="..\..\src\Linger.HttpClient.Standard\Linger.HttpClient.Standard.csproj" />
    </ItemGroup>

</Project>
