namespace Linger.HttpClient.Contracts.Models;

/// <summary>
/// 表示包含简单错误键值集合的 ProblemDetails 响应模型。
/// </summary>
/// <remarks>
/// 该类型用于 HTTP API 错误返回的标准化包装，<see cref="Errors"/> 字典可用于承载字段级错误信息。
/// </remarks>
/// <example>
/// <code>
/// var problem = new ProblemDetailsWithErrors
/// {
///     Type = "https://httpstatuses.com/400",
///     Title = "Validation Failed",
///     Status = 400,
///     Errors = { ["UserName"] = "Required" }
/// };
/// </code>
/// </example>
/// <summary>
/// RFC 7807 compliant ProblemDetails class supporting validation errors.
/// 符合 RFC 7807 标准、且支持字段验证错误的 ProblemDetails 实体类。
/// </summary>
public class ProblemDetailsWithErrors
{
    /// <summary>
    /// A URI reference that identifies the problem type.
    /// 错误类型的 URI（用于文档定位）。
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// 人类可读的错误大类标题（例如 "Validation Error"）。
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// The HTTP status code generated by the origin server.
    /// HTTP 状态码。
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// 针对本次错误的详细上下文解释（用户弹窗核心展现的内容、包含 Trace ID 等）。
    /// </summary>
    public string Detail { get; set; } = string.Empty;

    /// <summary>
    /// Standard ASP.NET Core dictionary of key-value pairs representing validation messages.
    /// 标准的 ASP.NET Core 字段验证错误集合（Key 为字段名，Value 为错误描述数组）。
    /// 必须为 string[] 才能百分百兼容框架自带的验证和 FluentValidation。
    /// </summary>
    public Dictionary<string, string[]> Errors { get; set; } = [];
}
