# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    #- name: Build
    #  run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    #- name: Publish NuGet
     # uses: brandedoutcast/publish-nuget@v2.5.5
      #with:
       # PROJECT_FILE_PATH: src/Linger/Linger.csproj
        #NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish to Nuget
      run: |
        dotnet build --configuration Release Linger.slnx
        dotnet pack Linger.slnx -c Release -o ./nupkg
        dotnet nuget push nupkg\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
